trigger: 
- none

name: "$(Build.DefinitionName)$(Rev:.r)"

pool:
  vmImage: ubuntu-latest

jobs:
- job: Apply
  timeoutInMinutes: 0
  steps:

  - task: Bash@3
    displayName: tfValidate
    inputs:
      filePath: .azdo-pipelines/scripts/terraform-with-backend.sh
      workingDirectory: $(WorkingDirectory)
      arguments: validate
    env:
      ARM_CLIENT_ID: $(ARM_CLIENT_ID)
      ARM_CLIENT_SECRET: $(ARM_CLIENT_SECRET)
      ARM_TENANT_ID: $(ARM_TENANT_ID)
      ARM_SUBSCRIPTION_ID: $(ARM_SUBSCRIPTION_ID)
      BACKEND_RESOURCE_GROUP_NAME: $(BACKEND_RESOURCE_GROUP_NAME)
      BACKEND_STORAGE_ACCOUNT_NAME: $(BACKEND_STORAGE_ACCOUNT_NAME)
      BACKEND_STORAGE_ACCOUNT_CONTAINER_NAME: $(BACKEND_STORAGE_ACCOUNT_CONTAINER_NAME)
      TF_BACKEND_KEY: $(ApplicationName)-$(EnvironmentName)

  - task: Bash@3
    displayName: tfApply
    inputs:
      filePath: .azdo-pipelines/scripts/terraform-with-backend.sh
      workingDirectory: $(WorkingDirectory)
      arguments: apply -auto-approve -var-file=_$(EnvironmentName).tfvars
    env:
      ARM_CLIENT_ID: $(ARM_CLIENT_ID)
      ARM_CLIENT_SECRET: $(ARM_CLIENT_SECRET)
      ARM_TENANT_ID: $(ARM_TENANT_ID)
      ARM_SUBSCRIPTION_ID: $(ARM_SUBSCRIPTION_ID)
      BACKEND_RESOURCE_GROUP_NAME: $(BACKEND_RESOURCE_GROUP_NAME)
      BACKEND_STORAGE_ACCOUNT_NAME: $(BACKEND_STORAGE_ACCOUNT_NAME)
      BACKEND_STORAGE_ACCOUNT_CONTAINER_NAME: $(BACKEND_STORAGE_ACCOUNT_CONTAINER_NAME)
      TF_BACKEND_KEY: $(ApplicationName)-$(EnvironmentName)

      